### ISSUE TITLE
Standardize org.eclipse.krazo.defaultViewFileExtension as javax.mvc.engine.defaultViewFileExtension

### ISSUE THREAD

**Issue by chkal** [jakartaee/mvc#38]
<a href="https://github.com/ngriffin7a"><img src="https://avatars2.githubusercontent.com/u/989387?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ngriffin7a](https://github.com/ngriffin7a)**
_Thursday May 02, 2019 at 19:32 GMT_
_Originally opened as https://github.com/mvc-spec/mvc-spec/issues/213_

----

As discussed in a [related Google Groups thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jsr371-users/ovd9d1Lx3xA/SXS8IGVNFAAJ), I recommend that the `org.eclipse.krazo.defaultViewFileExtension` feature be standardized as `javax.mvc.engine.defaultViewFileExtension`.

**Comment by erdlet** [comment]
Something for the next MVC release? Doesn't sound that much work

**Comment by chkal** [comment]
I'm not sure TBH if this feature is very popular. But I guess it would be a good candidate for inclusion.

**Comment by erdlet** [comment]
Don't know it either. TBH I'm not using that feature but saw that as quick win because it's "just" adding a constant

**Comment by erdlet** [comment]
@chkal what shall we do with this issue? I'm fine with both ideas, but I don't want to keep a zombie issue in the tracker ;)

**Comment by chkal** [comment]
Good question. I think it would really be helpful to hear other opinions about this.

@eclipse-ee4j/ee4j-mvc-committers Any thoughts?
