### ISSUE TITLE
Migration to jakartaee GitHub orga?

### ISSUE THREAD

**Issue by erdlet** [jakartaee/mvc#83]
I recognized that the specs are moving into the jakartaee GitHub orga. Think we shall do it too, @ivargrimstad?

**Comment by chkal** [comment]
I think most specs already migrated to the new orga. So from my point of view: Yes, we should move there too.

**Comment by erdlet** [comment]
@ivargrimstad Are there some kind of migration guide or prerequisites for this? Or do we just need to write a ticket for the admins so we get our repo?

**Comment by ivargrimstad** [comment]
I think it is just to create a ticket.
Remember to specify which repositories in the ticket. In our case it is the mvc-api and mvc-tck that should be moved

**Comment by ivargrimstad** [comment]
What about going forward with this now?

**Comment by erdlet** [comment]
Good idea, but unfortunately I've nearly no spare time at the moment because work and both kids take most of it.

It'd be great when someone else could take care of this.

**Comment by ivargrimstad** [comment]
I'll see if I can get it done over the weekend.

**Comment by erdlet** [comment]
Great thanks!

**Comment by arjantijms** [comment]
Move has been completed. Although auto redirects are in place, it's still advised to update the CI jobs to point to the new location directly.

**Comment by erdlet** [comment]
Thanks a lot for your help!

**Comment by arjantijms** [comment]
You're welcome!
